version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements-test.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-test.txt
      - run:
          name: setup Heroku
          command: bash .circleci/setup-heroku.sh
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            tox
